apiVersion: v1
kind: Service
metadata:
  name: {{  template "task.fullname" .  }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: web
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: {{ .Values.service.nodePort }}